authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),


]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('', include('recipes.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'myRecipes'

urlpatterns = [
    path('', views.home, name="home"),  # Home
    path('recipes/search/', views.search, name="search"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),  # recipes
    path('recipes/<int:id>/', views.recipes, name="recipe"),  # recipes
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Category (models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unity = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category,  # Foreign KEY
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True)  # Foreign KEY

    def __str__(self):
        return self.title

recipes/views.py
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from utils.recipes.pagination import make_pagination

from recipes.models import Recipe

# Create your views here.
PER_PAGE = int(os.environ.get('PER_PAGE', 6))


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def category(request, category_id):

    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        ).order_by('-id')
    )

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/category.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'title': f'Category | {recipes[0].category.name}'
    })


def recipes(request, id):

    recipe = get_object_or_404(
        Recipe.objects.filter(
            pk=id,
            is_published=True,
        )
    )

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_datail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),
        ),
        is_published=True,

    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'seach for "{search_term}"|',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'aditional_query': f'&q={search_term}',
    })

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://google.com" target="_blank">Eliveltonx</a>
    </div>
    <div class="powered">
        <a href="https://djangoproject.com/" target="_blank">Django Project</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}


    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Edu+VIC+WA+NT+Beginner:wght@700&display=swap"
      rel="stylesheet"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Edu+VIC+WA+NT+Beginner&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'global/css/global.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
      <h1>
        <a class="main-logo" href="{% url 'myRecipes:home' %}">
          <i class="fa-solid fa-burger main-logo-icon"></i>
          <span class="main-logo-text">My Recipes</span>
        </a>
      </h1>
    </div>
  </header>

recipes/templates/recipes/partials/message.html
{% if messages %}
<div class="main-content center container">
  {% for message in messages %}
    <div class="message {{ message.tags }}">
      {{message}}
    </div>
  {% endfor %}
</div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
<div class="container pagination">
    <div class="pagination-content">
        {% if pagination_range.first_page_out_of_range %}
            <a class="page-link page-item" href="?page=1{{aditional_query}}">
                1
            </a>
            <span class="page-item">...</span>
        {% endif %}
        {% for page in pagination_range.pagination %}
            {% if pagination_range.current_page == page %}
                <a class="page-link page-item page-current" href="?page={{page}}{{aditional_query}}">
                    {{page}}
                </a>
            {% else %}
                <a class="page-link page-item" href="?page={{page}}{{aditional_query}}">
                    {{page}}
                </a>
            {% endif %}
        {% endfor %}
        {% if pagination_range.last_page_out_of_range %}
            <span class="page-item">...</span>
            <a class="page-link page-item" href="?page={{pagination_range.total_page}}{{aditional_query}}">
                {{pagination_range.total_page}}
            </a>
        {% endif %}

    </div>
</div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
  <a href="{% url 'myRecipes:recipe' recipe.id %}">

    {% if recipe.cover.url is not Null  %}
    <div class="recipe-cover">
      <img
      src="{{recipe.cover.url}}"
      alt="temporario"
      />
    </div>
    {% else %}
      <p>SEM IMG</p>
    {% endif %}
  </a>
  
  <div class="recipe-title-container">
    <a href="{% url 'myRecipes:recipe' recipe.id %}">
      <h2 class="recipe-title">{{recipe.title}}</h2>
    </a>
  </div>
  <div class="recipe-autor">
    {% if recipe.author is not None %}
    <span class="recipe-autor-item">
      <i class="fas fa-user"></i>
      {{recipe.author.first_name}} {{recipe.author.last_name}}
    </span>
    {% else %}
    <span class="recipe-autor-item">
      <i class="fas fa-user"></i>
      *Anonimo*
    </span>
    {% endif %}
    <span class="recipe-autor-item">
      <i class="fas fa-calendar-alt"></i>
      {{recipe.created_at|date:"d/m/Y"}}
    </span>

    {% if recipe.category is not None %}
      <span class="recipe-autor-item">
        <a href="{%url 'myRecipes:category' recipe.category.id %}">
          <i class="fas fa-layer-group"></i>
          {{recipe.category.name}}
        </a>
      </span>
    {% endif %}

  </div>
  <div class="recipe-content">
    <p>
      {{ recipe.description }}
    </p>
  </div>
  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title">
        <i class="fas fa-stopwatch"></i>
        Preparo
      </h3>
      <div class="recipe-meta-text">{{recipe.preparation_time}} {{recipe.preparation_time_unity}}</div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3>
        <i class="fas fa-pizza-slice"></i>
        Porções
      </h3>
      <div class="recipe-meta-text">{{recipe.servings}}{{recipe.servings_unity}}</div>
    </div>
  </div>

  {% if is_datail_page is not True %}
  <div class="recipe-footer">
    <a
      class="recipe-read-more button button-dark button-full-width"
      href="{% url 'myRecipes:recipe' recipe.id %}"
    >
      <i class="fas fa-eye"></i>
      <span>Ver mais...</span>
    </a>
  </div>
  {% endif %}

  {% if is_datail_page is True %}

    <div class="preparation_steps">
      {% if recipe.preparation_steps_is_html is True %}
        {{recipe.preparation_steps|safe}}
      {% else %}
        <p>
          {{recipe.preparation_steps|linebreaksbr}}
        </p>
      {% endif %}

    </div>

  {% endif %}
  
  
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
      <form action="{%url 'myRecipes:search' %}" method="GET" class="search-form">
        <input type="search" class="search-input" name="q" value="{{ search_term }}" required>
        <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
      </form>
    </div>
  </div>