authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),


]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('', include('recipes.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name, '')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()


def add_placeholder(field, placeholder_val):
    add_attr(field, 'placeholder', placeholder_val)


def strong_password(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}$')

    if not regex.match(password):
        raise ValidationError((
            'Precisa tem uma letra min uma maiuscula e pelomenos 8'
        ),
            code='Invalid'
        )


class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'your username')
        add_placeholder(self.fields['email'], 'your Email')
        add_placeholder(self.fields['password'], '*****')
        add_placeholder(self.fields['first_name'], 'ex: John')
        add_placeholder(self.fields['last_name'], 'ex: Wick')
        add_attr(self.fields['username'], 'css', 'a-css-class')

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placehoder': 'Sua senha'
        }),
        error_messages={
            'required': 'password nao pode estar vazio'
        },
        help_text=(
            'Precisa tem uma letra min uma maiuscula e pelomenos 8'
        ),
        validators=[
            strong_password
        ]
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeate your password'
        }),
        label='Confirme Sua Senha',
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

    def clean_password(self):
        data = self.cleaned_data.get('password')

        if 'atencao' in data:
            raise ValidationError(
                'Não digite %(value)s no campo password',
                code='invalid',
                params={'value': 'atencao'}
            )
        return data

    def clean_first_name(self):
        data = self.cleaned_data.get('first_name')

        if 'jhon wick' in data:
            raise ValidationError(
                'Não digite %(value)s no campo first name',
                code='invalid',
                params={'value': 'jhon wick'}
            )
        return data

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise ValidationError({
                'password': ValidationError(
                    'password not match diferent',
                    code='invalid'
                ),
                'password2': 'password not match',
            })

authors/forms/login_form.py
from django import forms
from utils.django_forms import add_placeholder


class LoginForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'your username...')
        add_placeholder(self.fields['password'], 'your password...')

    username = forms.CharField()
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

authors/forms/register_form.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from utils.django_forms import add_attr, add_placeholder, strong_password


class RegisterForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['username'], 'your username')
        add_placeholder(self.fields['email'], 'your Email')
        add_placeholder(self.fields['password'], '*****')
        add_placeholder(self.fields['first_name'], 'ex: John')
        add_placeholder(self.fields['last_name'], 'ex: Wick')
        add_attr(self.fields['username'], 'css', 'a-css-class')

    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placehoder': 'Sua senha'
        }),
        error_messages={
            'required': 'password nao pode estar vazio'
        },
        help_text=(
            'Precisa tem uma letra min uma maiuscula e pelomenos 8'
        ),
        validators=[
            strong_password
        ]
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Repeate your password'
        }),
        label='Confirme Sua Senha',
    )

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

    def clean_password(self):
        data = self.cleaned_data.get('password')

        if 'atencao' in data:
            raise ValidationError(
                'Não digite %(value)s no campo password',
                code='invalid',
                params={'value': 'atencao'}
            )
        return data

    def clean_first_name(self):
        data = self.cleaned_data.get('first_name')

        if 'jhon wick' in data:
            raise ValidationError(
                'Não digite %(value)s no campo first name',
                code='invalid',
                params={'value': 'jhon wick'}
            )
        return data

    def clean_email(self):
        email = self.cleaned_data.get('email', '')
        exists = User.objects.filter(email=email).exists()

        if exists:
            raise ValidationError('Este email já esta em uso!')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            raise ValidationError({
                'password': ValidationError(
                    'password not match diferent',
                    code='invalid'
                ),
                'password2': 'password not match',
            })

authors/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from .forms import LoginForm, RegisterForm


# Create your views here.
def register_view(request):
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(request, 'authors/pages/register_view.html', {
        'form': form,
    })


def register_create(request):

    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, 'Seu usuario foi criado')

        del(request.session['register_form_data'])
        return redirect(reverse('authors:login'))

    return redirect('authors:register')


def login_view(request):
    form = LoginForm()
    return render(request, 'authors/pages/login.html', {
        'form': form,
        'form_action': reverse('authors:login_create')
    })


def login_create(request):
    if not request.POST:
        raise Http404()
    form = LoginForm(request.POST)
    login_url = reverse('authors:login')

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        if authenticated_user is not None:
            messages.success(request, 'Você esta logado.')
            login(request, authenticated_user)
            return redirect('authors:dashboard')

        messages.error(request, 'Invalid credentials')
        return redirect(login_url)

    messages.error(request, 'Error to validate your credentials')
    return redirect(login_url)


@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    if not request.POST:
        return redirect(reverse('authors:login'))

    if request.POST.get('username') != request.user.username:
        return redirect(reverse('authors:login'))

    logout(request)
    return redirect(reverse('authors:login'))


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard(request):
    return render(request, 'authors/pages/dashboard.html')

authors/templates/authors/pages/dashboard.html
{% extends 'global/base.html' %}
{% block title %}Dashboard | ({{user}}){% endblock title %}

{% block content %}

<div class="class main-content center container">
    <h2>Dashboard | ({{user}})</h2>
</div>

{% include 'recipes/partials/message.html' %}

    <div class="class main-content center container">
        <form action="{% url 'authors:register_create' %}" method = "POST">
            {% csrf_token %}
            <div class="class form-content-grid">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}


                {% if field.help_text %}
                <p class="class help-text">{{field.help_text}}</p>
                {% endif %}

                {{field.errors}}

                </div>
            {% endfor %}
            </div>
            {% if form.errors %}
            
            <div class="class form-content form-content-grid">
                <div class="class form-group">
                    <div class="message message-error">
                        Erros no formulario por favor corrija os erros
                    </div>
                </div>
            </div>

            {% endif %}


            <div class="class form-group">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

authors/templates/authors/pages/login.html
{% extends 'global/base.html' %}
{% block title %}Login |{% endblock title %}

{% block content %}

<div class="class main-content center container">
    <h2>Login</h2>

    {% if request.user.is_authenticated %}
        <div>Your are logged in with {{request.user.username}}...

            <form action="{% url 'authors:logout' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{request.user.username}}">
                <button type="submit">Click here</button>
            </form>to logout
        </div>
    {% endif %}
    
</div>

{% include 'recipes/partials/message.html' %}

    <div class="class main-content center container">
        <form action="{% url 'authors:login_create' %}" method = "POST">
            {% csrf_token %}
            <div class="class form-content-grid">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}


                {% if field.help_text %}
                <p class="class help-text">{{field.help_text}}</p>
                {% endif %}

                {{field.errors}}

                </div>
            {% endfor %}
            </div>
            {% if form.errors %}
            
            <div class="class form-content form-content-grid">
                <div class="class form-group">
                    <div class="message message-error">
                        Erros no formulario por favor corrija os erros
                    </div>
                </div>
            </div>

            {% endif %}


            <div class="class form-group">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

authors/templates/authors/pages/register_view.html
{% extends 'global/base.html' %}
{% block title %}Register |{% endblock title %}

{% block content %}

<div class="class main-content center container">
    <h2>Register</h2>
</div>

{% include 'recipes/partials/message.html' %}

    <div class="class main-content center container">
        <form action="{% url 'authors:create' %}" method = "POST">
            {% csrf_token %}
            <div class="class form-content-grid">
            {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}


                {% if field.help_text %}
                <p class="class help-text">{{field.help_text}}</p>
                {% endif %}

                {{field.errors}}

                </div>
            {% endfor %}
            </div>
            {% if form.errors %}
            
            <div class="class form-content form-content-grid">
                <div class="class form-group">
                    <div class="message message-error">
                        Erros no formulario por favor corrija os erros
                    </div>
                </div>
            </div>

            {% endif %}


            <div class="class form-group">
                <button type="submit">Enviar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}